dist: jammy
language: php
php:
  - '8.2'
before_script: composer install; cd test
script: phpunit --exclude-group nontravis .
after_success:
  - "../trigger_travis_build.sh kinikit-mvc"
  - "../trigger_travis_build.sh kinikit-persistence"
env:
  global:
    secure: AznXBp1kUC1XDLsJknqkWbzSUJJCfI1FbJyk73glyhERTfY7LLDukeURXAo/NgKfNURGMLSKWVWJLJKX8CUtCeSZzQ6sfK7+CRHn7gCPjMurI4rASF0OoKBARmVqiPeMtYcY58Vzj313PYxExWwkv0IJA9srEfiqJYPdgGmjSBcqbvY+lmJp/zogS+qUBHaVKbtwSUxzwEx0uAk6+gSqULrjXu+k27YFQwri3W7lmy9yxw0A0F08alFqLi59nd0VetvA5Var6h/Ido4U589eH+Qx3BeM+ZazwjjCL5yVMAwjFfzx1i5EPReQ/m9+2pTwDLdpQzwuLpFQ24wrduSXhsUkxNfVPwoLu9goEjQOodZoNnllsI2YB3Tfv63BR5Rh2s7YdZ2ALs6dVV1bc87DbIHVfrU2XOLJgfhUJcfjdkTmZZ7ZYpGtnvoXM7bH6w5dii1YCEIOh70GgjWlnqenVMhlgli9SIqNtGQf5E+c/hvUpLam7OVvEY7iyQm+XetThlK3z43QMePrUHZn4tkvYP/ACt/KGhNKQtGa6bs3cXwGTcfHy45pwBw+j5UBnW1RZdQBZKdSaaE8QDz3jrL0o1vCz9MNescspVSbYlWcLhZ7FlQ7dfJTom2gAwkeldPgqw50cfVZwA+gM4ZuIdSPQ1kLiAEPSltrDOx8Z720aCw=
notifications:
  slack:
    secure: ZRGuoZzfAhiLdKh5ihnyy6xXrfJHNRFYeHv6Ai7FU6Bj3n5OS4HQiX4iohOHA8RJIVGa0PD9oJaahqi0jyZ4K377VOo2BwzfhsK6CPFduM9qNNUWPKHMqnQKx98SibKZGlrzyuTuWUxBz5i3BYXWhhykj4pGwW9omOIvET3gQl5GTlNAABrAnfWSl1TfhZxNgU6y41lVoFcLbVUNZtSG0RPg06R2qMezJdpGmcBZY1xGyS/uhi/8OAu05hrAVtNzneEmtzo3x3Bi3ZOX45SJ7ox3+ZuaXZ1A4XIzvg833C5KhTcrcW/zYOsX3q/x7P7mC8z5OPY7ojvnI6AffENZlAS2ChE0Sv5+tVkTxs3sL5PsfRjHTJRRBVE/LX0fEUGtgyvH17rV06P8mTFkAnqNPxQrYC8BS4OsIYS+BiAc88iBNeHS2N8mxdQakFy0gJjv4bjXQDfmg3YY0ml4AuIWIfVpn4WEl7gO265CLhqBTc553NxRyYmOts875Ckhv+wov5i52Kigb+PFlbP7mVnBPAW8myo2Bh2dHUIAuXubdqO/MCtd7e1mC1toV3fsqAN/T+BarjOlranckLvf//IL6vxM5W06Ny77IiEgRQMJQMvPWue8lgQDkNiLvu52xm+eaS/AMyxpZq3MkGE9iOgvCd9Zr3ZaoZCd+vWNto2CrrQ=
